### ISSUE TITLE
ISST:ESS5351C:ess6:ems6/essio62: POWERHW component flagging an initial power cord disconnected, when there was only one disconnected.

### ISSUE THREAD

**Issue by rudydev** [open-power-ref-design-toolkit/ibm-crassd#4]
PROBLEM SUMMARY

ISST:ESS5351C:ess6:ems6/essio62: POWERHW component flagging an initial power cord disconnected, when there was only one disconnected.

I was testing validation of the powerhw component ans the monitoring seems that initially one power AC got flagged as disconnected. We only removed the second one, not the initial one.

Examples:
[root@ems6 gss]# vi /var/mmfs/mmsysmon/mmsysmonitor.conf
[root@ems6 gss]# mmsysmoncontrol restart
[root@ems6 gss]# echo $?
0
[root@ems6 gss]# mmsysmoncontrol status
\u25cf mmsysmon.service - Spectrum Scale Monitoring Service
   Loaded: loaded (/usr/lib/systemd/system/mmsysmon.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-02-13 15:53:25 CST; 9s ago
  Process: 46997 ExecStop=/usr/lpp/mmfs/bin/mmsysmonc d shutdown (code=exited, status=0/SUCCESS)
  Process: 47010 ExecStart=/usr/lpp/mmfs/bin/mmsysmon.py (code=exited, status=0/SUCCESS)
 Main PID: 47012 (mmsysmon.py)
    Tasks: 30
   CGroup: /system.slice/mmsysmon.service
           \u2514\u250047012 /usr/bin/python2 /usr/lpp/mmfs/bin/mmsysmon.py

Feb 13 15:53:24 ems6 systemd[1]: Starting Spectrum Scale Monitoring Service...
Feb 13 15:53:24 ems6 systemd[1]: PID file /var/mmfs/run/mmsysmonPid not readable (yet?) after start.
Feb 13 15:53:25 ems6 systemd[1]: Started Spectrum Scale Monitoring Service.
Feb 13 15:53:33 ems6 mmsysmon[47012]: [I] Event raised: The state of component NATIVE_RAID changed to HEALTHY.
Feb 13 15:53:33 ems6 mmsysmon[47012]: [I] Event raised: The state of component CES changed to HEALTHY.
Feb 13 15:53:33 ems6 mmsysmon[47012]: [I] Event raised: The state of this node changed to HEALTHY.
Feb 13 15:53:33 ems6 mmsysmon[47012]: [I] Event raised: The state of component POWERHW changed to CHECKING.
Feb 13 15:53:34 ems6 mmsysmon[47012]: [I] Event raised: The IBM Spectrum Scale monitoring service has been started
[root@ems6 gss]# mmhealth node show

Node name:      ems6-ib.hst.ibm.net
Node status:    TIPS
Status Change:  Now

Component      Status        Status Change     Reasons

GPFS           TIPS          Now               gpfs_maxstatcache_low
NETWORK        HEALTHY       Now               -
FILESYSTEM     HEALTHY       Now               -
POWERHW        HEALTHY       Now               -

Now we will test removing one power cord from essio62:

testing / validating POWERHW monitoring: 02/13/2020

[root@ems6 gss]# mmhealth node show

Node name:      ems6-ib.hst.ibm.net
Node status:    TIPS
Status Change:  20 min. ago

Component      Status        Status Change     Reasons

GPFS           TIPS          20 min. ago       gpfs_maxstatcache_low
NETWORK        HEALTHY       20 min. ago       -
FILESYSTEM     HEALTHY       20 min. ago       -
POWERHW        DEGRADED      20 min. ago       srv_power_ac_lost(essio62/1)

then we unplugged

[root@ems6 gss]# mmhealth node show

Node name:      ems6-ib.hst.ibm.net
Node status:    TIPS
Status Change:  23 min. ago

Component      Status        Status Change     Reasons

GPFS           TIPS          23 min. ago       gpfs_maxstatcache_low
NETWORK        HEALTHY       23 min. ago       -
FILESYSTEM     HEALTHY       23 min. ago       -
POWERHW        DEGRADED      22 min. ago       srv_power_ac_lost(essio62/2, essio62/1)
[root@ems6 gss]#

[root@ems6 gss]# mmhealth node show POWERHW --verbose

Node name:      ems6-ib.hst.ibm.net

Component     Status        Status Change            Reasons

POWERHW       DEGRADED      2020-02-13 15:54:02      srv_power_ac_lost(essio62/2, essio62/1)

Event                 Parameter     Severity    Active Since             Event Message

srv_power_ac_lost     POWERHW       WARNING     2020-02-13 16:14:50      The power supply essio62/2's line cord was disconnected.
srv_power_ac_lost     POWERHW       WARNING     2020-02-13 15:54:02      The power supply essio62/1's line cord was disconnected.
srv_power_active      POWERHW       INFO        2020-02-13 15:53:38      Power supply essio61/1 is active.
[root@ems6 gss]# 

the weird part is that initially we had both power cords connected.

Not sure why initially was triggering both as disconnected.
Please advise ...
BUILD DETAILS:

Start of install check
nodelist: ems6 essio61 essio62

Node: ems6 Installed version: 5.3.5.1C-20200205T051955Z_ppc64le_datamanagement
Node: essio61 Installed version: 5.3.5.1C-20200205T051955Z_ppc64le_datamanagement
Node: essio62 Installed version: 5.3.5.1C-20200205T051955Z_ppc64le_datamanagement

=== mmdiag: version ===
Current GPFS build: 5.0.4.2 200129.102713.
Built on Jan 29 2020 at 10:30:10
Running 2 days 21 hours 19 minutes 9 secs, pid 33096
Linux ems6 4.14.0-115.17.1.el7a.ppc64le #1 SMP Tue Dec 17 18:04:10 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
SYSTEM DETAILS [Server details with credentials]:

Server[Credentails] :

Access for all nodes:

    ssh root@9.41.168.128 (root/cluster)
    ssh (root/cluster)

GPFS cluster information
........................
GPFS cluster name: ess6.hst.ibm.net
GPFS cluster id: 1133330850331883091
GPFS UID domain: ess6.hst.ibm.net
Remote shell command: /usr/bin/ssh
Remote file copy command: /usr/bin/scp
Repository type: CCR

Node Daemon node name IP address Admin node name Designation
...........................................................................................
1 essio61.ib.hst.ibm.net 192.168.100.61 essio61.ib.hst.ibm.net quorum.manager
2 essio62.ib.hst.ibm.net 192.168.100.62 essio62.ib.hst.ibm.net quorum.manager
3 ems6.ib.hst.ibm.net 192.168.100.60 ems6.ib.hst.ibm.net quorum
4 essio61.vm1.ib.hst.ibm.net 192.168.100.64 essio61.vm1.ib.hst.ibm.net
5 essio62.vm1.ib.hst.ibm.net 192.168.100.65 essio62.vm1.ib.hst.ibm.net

Environment details :

EMS: ems6
IO Nodes: essio61,essio62

Date / Time of problem
date: 02/13/20, time: 21:05:39
STEPS [How to recreate the problem with log snippets]:

See above in problem summary
EXPECTED RESULT:

See above in problem summary
LOGs LOCATION [Upload any files/dumps to the /DUMPS directory on c5dump1.pok.stglabs.ibm.com or c5dump2.pok.stglabs.ibm.com.

Logs are either attached to the defect report or located in the /DUMPS/defectNo/. of the system under test
OBSERVATION [If Applicable]:

See above in problem summary

**Comment by rudydev** [comment]
ok so now I am going to reconnect the cable I pulled from essio62:

before reconnecting:
```
[root@ems6 gss]# mmhealth node show POWERHW --verbose

Node name:      ems6-ib.hst.ibm.net

Component     Status        Status Change            Reasons
---------------------------------------------------------------------------------------------------------
POWERHW       DEGRADED      2020-02-13 15:54:02      srv_power_ac_lost(essio62/2, essio62/1)

Event                 Parameter     Severity    Active Since             Event Message
---------------------------------------------------------------------------------------------------------------------------------
srv_power_ac_lost     POWERHW       WARNING     2020-02-13 16:14:50      The power supply essio62/2's line cord was disconnected.
srv_power_ac_lost     POWERHW       WARNING     2020-02-13 15:54:02      The power supply essio62/1's line cord was disconnected.
srv_power_active      POWERHW       INFO        2020-02-13 15:53:38      Power supply essio61/1 is active.
```

**Comment by rudydev** [comment]
after connecting it back:

```
[root@ems6 gss]# mmhealth node show POWERHW --verbose

Node name:      ems6-ib.hst.ibm.net

Component     Status        Status Change            Reasons
----------------------------------------------------------------------------------------------
POWERHW       DEGRADED      2020-02-13 15:54:02      srv_power_ac_lost(essio62/1)


Event                     Parameter     Severity    Active Since             Event Message
-------------------------------------------------------------------------------------------------------------------------------------
srv_power_ac_lost         POWERHW       WARNING     2020-02-13 15:54:02      The power supply essio62/1's line cord was disconnected.
srv_power_ac_restored     POWERHW       INFO        2020-02-13 16:31:30      The power supply essio62/2's AC connection restored
srv_power_active          POWERHW       INFO        2020-02-13 15:53:38      Power supply essio61/1 is active.
[root@ems6 gss]# mmhealth node show POWERHW --verbose --resync
```

**Comment by rudydev** [comment]
we tried --resync

```
[root@ems6 gss]# mmhealth node show POWERHW --verbose --resync
Resend events to cluster state manager
[root@ems6 gss]# 
[root@ems6 gss]# 
[root@ems6 gss]# mmhealth node show POWERHW --verbose

Node name:      ems6-ib.hst.ibm.net

Component     Status        Status Change            Reasons
----------------------------------------------------------------------------------------------
POWERHW       DEGRADED      2020-02-13 15:54:02      srv_power_ac_lost(essio62/1)


Event                     Parameter     Severity    Active Since             Event Message
-------------------------------------------------------------------------------------------------------------------------------------
srv_power_ac_lost         POWERHW       WARNING     2020-02-13 15:54:02      The power supply essio62/1's line cord was disconnected.
srv_power_ac_restored     POWERHW       INFO        2020-02-13 16:42:19      The power supply essio62/2's AC connection restored
srv_power_active          POWERHW       INFO        2020-02-13 15:53:38      Power supply essio61/1 is active.
[root@ems6 gss]# 
```

but not sure ...

**Comment by thalerj** [comment]
It looks like this is a syncing of the state issue. Likely there was a log entry for the ac being lost on the first power supply. Can you double check the BMC logs to see if an alert was posted there, but perhaps before you started your test?

**Comment by rudydev** [comment]
sorry did not see the posting from 3 days ago....
so im looking at the bmc event logs and sensor stuff in the GUI, i do not see anomaly... could have been the sync of the state you mentioned.

**Comment by rudydev** [comment]
weird, that i noticed the /var/mmfs/mmsysmon/mmsysmonitor.conf
did not have the powerhw_enabled=true

probably you unset it (if not you, then who knows)


I configured again

```
[root@ems6 ~]# mmhealth node show powerhw -N ems6-ib,essio61-ib,essio62-ib --verbose

Node name:      ems6-ib.hst.ibm.net

Component     Status        Status Change            Reasons
------------------------------------------------------------
POWERHW       HEALTHY       2020-02-24 09:48:45      -


Event                Parameter     Severity    Active Since             Event Message
---------------------------------------------------------------------------------------------------------
srv_power_active     POWERHW       INFO        2020-02-24 09:48:45      Power supply essio61/1 is active.

Node name:      essio61-ib.hst.ibm.net

Component     Status        Status Change            Reasons
------------------------------------------------------------
POWERHW       CHECKING      2020-02-24 09:52:31      -

There are no active events for the component POWERHW on this node (essio61-ib.hst.ibm.net).

Node name:      essio62-ib.hst.ibm.net

Component     Status        Status Change            Reasons
------------------------------------------------------------
POWERHW       CHECKING      2020-02-24 09:52:27      -

There are no active events for the component POWERHW on this node (essio62-ib.hst.ibm.net).
[root@ems6 ~]#
```
is all right now ...

**Comment by thalerj** [comment]
@rudydev np! I was also slow on the initial response. It looks like it's working correctly. I'm going to leave this issue open temporarily. If you do rerun the test and observe the same behavior please let me know. 

Also I haven't edited any of the configuration on the system, so I'm not sure why that configuration variable was set.

**Comment by rudydev** [comment]
yeah is working ... We marked it passing. I will close the issue. On the next release we will re-test it to make sure.

Thanks!
